#pragma kernel NoiseEditorOld
#include "/Includes/MathOld.compute"
#include "/Includes/NoiseOld.compute"

struct WGEditorOutputGPU
{
    int coord[2];
    float voronoiHeight;
    float normHeight;
    float voronoiMatchHeight;
    float combinedHeight;
    float subHeight;
    float subVoronoiMatchHeight;
    float subCombinedHeight;
};

//Output
RWStructuredBuffer<WGEditorOutputGPU> Result;

//Shared data
int3 ChunkCoord;

[numthreads(8, 8, 1)]
void NoiseEditorOld(uint3 id : SV_DispatchThreadID)
{
	//Local space coord
    int index = IndexByCoord(id.x, id.y, id.z);
	int3 coord = CoordByIndex(index);

	//World space coord
	int chunkCoordX = (ChunkCoord.x * ThreadDimensions.x) + coord.x;
	int chunkCoordY = (ChunkCoord.y * ThreadDimensions.y) + coord.y;

	//Voronoi map
	int regionIndexes[3];
	float voronoiHeight = Voronoi(chunkCoordX, chunkCoordY, regionIndexes);
	
	//Normal map
    float normHeight = Perlin(chunkCoordX, chunkCoordY, MapOctaveOffsets);
    float voronoiMatchHeight = BiomeBlendView(normHeight, voronoiHeight, float2(chunkCoordX, chunkCoordY), regionIndexes, false, false);
    float combinedHeight = BiomeBlend(normHeight, voronoiHeight, float2(chunkCoordX, chunkCoordY), regionIndexes, false);

	//Subtractive map
    float subHeight = Perlin(chunkCoordX, chunkCoordY, SubMapOctaveOffsets);
    float subVoronoiMatchHeight = BiomeBlendSubtrativeView(subHeight, voronoiHeight, float2(chunkCoordX, chunkCoordY), regionIndexes, true, false);
    float subCombinedHeight = BiomeBlendSubtrative(subHeight, voronoiHeight, float2(chunkCoordX, chunkCoordY), regionIndexes, true);

    Result[index].coord[0] = chunkCoordX;
    Result[index].coord[1] = chunkCoordY;
    Result[index].voronoiHeight = voronoiHeight;
    Result[index].normHeight = normHeight;
    Result[index].voronoiMatchHeight = voronoiMatchHeight;
    Result[index].combinedHeight = combinedHeight;
    Result[index].subHeight = subHeight;
    Result[index].subVoronoiMatchHeight = subVoronoiMatchHeight;
    Result[index].subCombinedHeight = subCombinedHeight;
}